export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_ACTIVITY = "GET_ACTIVITY";
export const GET_COUNTRY_BY_NAME = "GET_COUNTRY_BY_NAME";

export const FILTER_BY_REGION = "FILTER_BY_REGION";
export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY";

export const ORDEN_ALPHA = "ORDEN_ALPHA_ASC";
export const ORDEN_POPULATION = "ORDEN_POPULATION";
